/// \file docs.h Used to generate the main page of the documentation

/** \mainpage wxAccordion

\section intro Introduction

This library provides the wxAccordion class, which as the name suggests, is an accordion style container control for the wxWidgets library.  This is a very simple implementation: the expanding and collapsing mechanism uses nothing but sizers and panels.  The control is derived from wxBookCtrlBase so that a programmer familiar wxNotebook or wxAuiNotebook should already be comfortable this class as well.

Although this class can't provide all the freedom a programmer would have for building an accordion with HTML/CSS, there is a wide variety of commands for modifying the behavior, layout, and appearance of the control.  For example, the caption bars can be drawn with a gradient of 2 or more colors or can use an image file for the background.  The caption bars can optionally contain expand/collapse buttons and icons.  Here are a few examples of accordions that can be produced with this library:

\image html samples.png

\section ackn Acknowledgements

I've included enough headers with this documentation to generate wxAccordion's entire inheritance hierarchy.  The copyright for those headers obviously belong the wxWidgets project and their respective writers. 

The original idea for this control and some of the names for the style options came from the excellent <a href="http://wxcode.sourceforge.net/showcomp.php?name=foldbar" title="The Wikipedia article on the accordion graphical control element.">foldbar</a> library currently hosted on wxCode. 





 */
 
/// \class wxAccordion accordion.h <wx/accordion/accordion.h>
/// This class represents an accordion control, which manages multiple windows with associated caption bars.  See <a href="https://en.wikipedia.org/wiki/Accordion_%28GUI%29" title="The Wikipedia article on the accordion graphical control element.">Wikipedia</a> for more information.
/// 
/// To use the class, create a wxAccordion object and call wxAccordion::AddPage or wxAccordion::InsertPage, passing a window to be used as the page. Do not explicitly delete the window for a page that is currently managed by wxAccordion.
/// ## Styles
/// This class supports the following styles:
/// \li <span class="style">wxAC_BUTTON_LEFT</span>:<div class="styleDesc"> The expand and collapse buttons, if used, are placed on the left side of the caption bar. </div>
/// \li <span class="style">wxAC_SINGLE_FOLD</span>:<div class="styleDesc"> When a page is expanded, all other pages are collapsed. </div>
/// \li <span class="style">wxAC_COLLAPSE_TO_BOTTOM</span>:<div class="styleDesc"> The accordion's pages are pushed to the bottom of the containing window. </div>
/// \li <span class="style">wxAC_FLOAT_TO_TOP</span>:<div class="styleDesc"> Pages are moved to the top of the page set when they are expanded and restored to their original position when collapsed. </div>
///
/// ## Events emitted by this class
/// The following event handler macros redirect the events to member function handlers '<b>func</b>' with prototypes like:
/// <div class="eventHandler"><span>void&nbsp;handlerFuncName(<a class="el" href="classwx_book_ctrl_event.html" title="This class represents the events generated by book controls (wxNotebook, wxListbook, wxChoicebook, wxTreebook, wxAuiNotebook).">wxBookCtrlEvent</a>&amp;&nbsp;event)</span></div>
/// Event macros for events emitted by this class:
/// \li <span class="event">EVT_ACCORDION_COLLAPSED(id,  func)</span>:<div class="eventDesc">The page selection was collapsed.  Processes a <code>wxEVT_ACCORDION_COLLAPSED</code> event. </div></li>
/// \li <span class="event">EVT_ACCORDION_COLLAPSING(id,  func)</span>:<div class="eventDesc">The page selection is about to be collapsed. Processes a <code>wxEVT_ACCORDION_COLLAPSING</code> event. This event can be vetoed. </div></li>
/// \li <span class="event">EVT_ACCORDION_EXPANDED(id,  func)</span>:<div class="eventDesc">The page selection was expanded. Processes a <code>wxEVT_ACCORDION_EXPANDED</code> event. </div></li>
/// \li <span class="event">EVT_ACCORDION_EXPANDING(id,  func)</span>:<div class="eventDesc">The page selection is about to be expanded. Processes a <code>wxEVT_ACCORDION_EXPANDING</code> event. This event can be vetoed. </div></li>
 
 
/// \class wxAccordionStyle accordion.h <wx/accordion/accordion.h>
/// This class encapsulates the colours, bitmap, and font used for drawing a  wxAccordion's caption bars and pages.
/// 
/// \sa wxAccordion
 
/// \enum wxAccordionToggleStyle
/// \brief The behavior of the accordion in response to mouse clicks on the caption bar.
///
/// These values are only used if an expand or collapse button is shown.
/// If no button is visible, the accordion will always toggle for any click
/// on a caption bar.
 
/// \enum wxAccordionBorderStyle
/// \brief The border style options for the accordion's caption bars.
///
 
/// \enum wxAccordionHighlighting
/// \brief The behavior of the accordion when the mouse is over a caption bar.
///
 
/// \enum wxAccordionDisabledState
/// \brief The style options of a caption bar in the disabled state.
///
 